### ISSUE TITLE
Does not compile on RPI3

### ISSUE THREAD

**Issue by joriws** [jpirko/restmbmaster#1]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

--

automake + configure + make

restmbmaster $ make
Making all in src
make[1]: Entering directory '/home/pi/restmbmaster/restmbmaster/src'
  CC       restmbmaster-restmbmaster.o
restmbmaster.c:431:24: error: return type is an incomplete type
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c: In function ‘rmm_ahcb’:
restmbmaster.c:474:11: warning: ‘return’ with a value, in function returning void
    return MHD_YES;
           ^~~~~~~
restmbmaster.c:431:24: note: declared here
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c:481:13: warning: ‘return’ with a value, in function returning void
      return MHD_NO;
             ^~~~~~
restmbmaster.c:431:24: note: declared here
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c:486:12: warning: ‘return’ with a value, in function returning void
     return MHD_YES;
            ^~~~~~~
restmbmaster.c:431:24: note: declared here
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c:492:10: warning: ‘return’ with a value, in function returning void
   return MHD_NO;
          ^~~~~~
restmbmaster.c:431:24: note: declared here
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c:626:10: warning: ‘return’ with a value, in function returning void
   return MHD_NO;
          ^~~~~~
restmbmaster.c:431:24: note: declared here
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c:630:10: warning: ‘return’ with a value, in function returning void
   return MHD_NO;
          ^~~~~~
restmbmaster.c:431:24: note: declared here
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c:634:9: warning: ‘return’ with a value, in function returning void
  return err;
         ^~~
restmbmaster.c:431:24: note: declared here
 static enum MHD_Result rmm_ahcb(void *cls, struct MHD_Connection *connection,
                        ^~~~~~~~
restmbmaster.c: In function ‘rmm_webserver_init’:
restmbmaster.c:688:9: warning: passing argument 5 of ‘MHD_start_daemon’ from incompatible pointer type [-Wincompatible-pointer-type ]
         &rmm_ahcb, rmm,
         ^~~~~~~~~
In file included from restmbmaster.c:35:
/usr/include/microhttpd.h:2185:1: note: expected ‘MHD_AccessHandlerCallback’ {aka ‘int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, unsigned int *, void **)’} but argument is of type ‘void (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)’ {aka ‘void (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, unsigned int *, void **)’}
 MHD_start_daemon (unsigned int flags,
 ^~~~~~~~~~~~~~~~
make[1]: *** [Makefile:384: restmbmaster-restmbmaster.o] Error 1
make[1]: Leaving directory '/home/pi/restmbmaster/restmbmaster/src'
make: *** [Makefile:349: all-recursive] Error 1

**Comment by joriws** [comment]
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
./configure: line 4597: LT_INIT: command not found
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBMODBUS... yes
checking for LIBMICROHTTPD... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for inline... inline
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: executing depfiles commands

**Comment by jpirko** [comment]
you should update your libmicrohttpd
